; Part timing data (9 songs x 2 bytes, little-endian frame counts)
; 985248 cycles per second
;  19656 cycles per frame
        .word   $BB44               ; Song 1: 942,308,640 cycles, 15:56.42 (15:56.42)
        .word   $7234               ; Song 2: 574,662,816 cycles,  9:43.27 (25:39.69)
        .word   $57C0               ; Song 3: 441,552,384 cycles,  7:28.16 (33:07.85)
        .word   $88D0               ; Song 4: 688,431,744 cycles, 11:38.74 (44:46.59)
        .word   $C0A4               ; Song 5: 969,355,296 cycles, 16:23.87 (61:10.46)
        .word   $79F6               ; Song 6: 613,699,632 cycles, 10:22.89 (71:33.35)
        .word   $491A               ; Song 7: 367,842,384 cycles,  6:13.35 (77:46.70)
        .word   $7BF0               ; Song 8: 623,645,568 cycles, 10:32.98 (88:19.68)
        .word   $0100               ; Song 9:           ? cycles,  9:21.?? (97:40.68)
